#!/bin/sh
#
# Updates the version code

cd "$(dirname "$0")"
cd "$(git rev-parse --show-toplevel)"

git_desc=$(git describe --tags --long --match "v*")
version=$(echo "$git_desc" | sed 's:v\(.*\)-\(.*\)-.*:\1.\2:')
short_version=$(echo "$git_desc" | sed 's:v\([^-]*\).*:\1:')
major=$(echo "$git_desc" | sed 's:v\(.*\)\.\(.*\)\..*:\1:')
minor=$(echo "$git_desc" | sed 's:v\(.*\)\.\(.*\)\..*:\2:')

version_tag=`echo $version | tr . _`

gen_tagged_addon() {
    classname=$1
    echo "    [KSPAddonFixed(KSPAddon.Startup.Instantly, false, typeof(${classname}_${version_tag}))]"
}

gen_tagged_class() {
    classname=$1
    echo "    internal class ${classname}_${version_tag} : ${classname} { }"
}

gen_tagged_class_wrappers() {
    echo "using System;"
    echo "using System.Collections.Generic;"
    echo "using System.Linq;"
    echo "using System.Reflection;"
    echo "using UnityEngine;"
    echo "namespace KSPAPIEL {"
    echo "    [KSPAddon(KSPAddon.Startup.Instantly, true)]"
    gen_tagged_class UIPartActionsExtendedRegistration
    gen_tagged_class UIPartActionResourceEditorImproved
    gen_tagged_class UIPartActionLabelImproved
    gen_tagged_class UIPartActionFloatEdit
    gen_tagged_class UIPartActionChooseOption
    echo "    [KSPAddon(KSPAddon.Startup.Instantly, true)]"
    gen_tagged_class CompatibilityChecker
    echo "}"
}

sed -e "s/@VERSION@/$version/;s/@MAJOR/$major/;s/@MINOR/$minor/" Source/Properties/AssemblyInfo.in > tmp
cmp -s Source/Properties/AssemblyInfo.cs tmp || cp tmp Source/Properties/AssemblyInfo.cs

#sed -e "s/@VERSION@/$short_version/" ProceduralParts.version.in > tmp
#cmp -s ProceduralParts.version tmp || cp tmp ProceduralParts.version

gen_tagged_class_wrappers > tmp
cmp -s Source/tagged_classes.cs tmp || cp tmp Source/tagged_classes.cs

rm tmp
